type Member = {
  id: string;
  firstname: string;
  middlename?: string;
  lastname: string;
  position: string;
  email?: string;
  website?: string;
  avatar?: string;
  shortbio?: string;
  office?: string;
  gscholar?: string;
  orcid?: string;
  github?: string;
  linkedin?: string;
  twitter?: string;
  facebook?: string;
  instagram?: string;
  youtube?: string;
};